waypoint:
  P1:
    x: 12.19
    y: 8.73
  P2:
    x: 25.04
    y: 4.36
  P3:
    x: 28.62
    y: -6.17
  P4:
    x: 11.63
    y: -16.85
  P5a:
    x: 7.64
    y: -5.55
  P5b:
    x: 27.48
    y: -13.65

scientific:
  S1:
    x: null
    y: null
