name: Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FREEDOM_URL: ${{ secrets.FREEDOM_URL }}
        with:
          name: denizugur/asd_driver/asd_image
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          cache: true
          buildargs: FREEDOM_URL
